name = "Guan Yu"
license = "MIT"
licenselink = "https://github.com/bekzatbaubek/guanyu/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = ["blog", "personal"]
features = []
min_version = "0.41.0"

[author]
  name = "Bekzat Baubek"
  homepage = "https://baubek.com"

